Server:
    RunMode: debug
    HttpPort: 8080
    ReadTimeout: 30
    WriteTimeout: 30

App:
    DefaultPageSize: 10
    MaxPageSize: 100
    LogSavePath: storage/logs
    LogFileName: app
    logFileExt: log
    UploadSavePath: storage/uploads
    UploadServerUrl: http://127.0.0.1:8080/static
    UploadImageMaxSize: 5 # 单位m
    UploadImageAllowExts:
        - .jpeg
        - .jpg
        - .png

Database:
    DBType: mysql
    Host: mysql
    Port: 3306
    Username: root
    Password: ""
    DBName: blog
    TablePrefix: blog_
    Charset: utf8
    ParseTime: true
    Loc: Local
    MaxIdleConns: 10
    MaxOpenConns: 30

Jwt:
    Secret: abksier039sKDJFJ093rkFDn
    Issuer: blog-service
    Expire: 7200